### ISSUE TITLE
DtabaseAdapter; $use_table_alias ignored in nested where clause

### ISSUE THREAD

**Issue by SiLVA-Project** [tombenner/wp-mvc#101]
Method:

recursive call of $clauses = $this->get_where_sql_clauses($value); loses $use_table_alias info,

Error:
WordPress-Datenbank-Fehler: [Unknown column 'ModelName.id' in 'where clause']
DELETE FROM `wp_course_model_name` WHERE id != "41" AND (ModelName.id != "40" AND (ModelName.id != "37" AND (ModelName.xxx_id = "1"))) 

Suggestion on first try: call $this->get_where_sql_clauses($value, $options); instead

**Comment by cyberscribe** [comment]
Thanks. If you would like to submit a pull request I would be happy to review the code!
