### ISSUE TITLE
Object retrieve by "find" method ?

### ISSUE THREAD

**Issue by vrcAlbert** [tombenner/wp-mvc#102]
Hi,

from what I saw, all the "find" methods retrieve a "MvcModelObject" (because of how _process_objects_ method works).

Why does'nt it retrieve an object of the very same nature that the one used to query ?

As a consequence, we would be able to do something like :
```
$model = mvc_model($class);
$model->find_by_email($email);
$model->save($updated_data);
```

Thanks in advance for your explanation :)

**Comment by cyberscribe** [comment]
Sorry, I'm not quite sure what you are asking.

This should work to update one value for one object found by email address:

`$model = mvc_model($class);
$result = $model->find_one_by_email($email);
$result->some_value = 'some_new_value';
$model->save($result);`

**Comment by vrcAlbert** [comment]
Thanks for your reply, I did not understand how it was supposed to work.

Thanks again :)
