### ISSUE TITLE
MvcModel validation only takes place while updating object

### ISSUE THREAD

**Issue by simonvomeyser** [tombenner/wp-mvc#108]
Hi there and a big compliment on your fine work!

I have a question concerning the validation of a model while saving it using save():

It seems that the function validate_data() is only called when the object already exists(an id is passed in the data-array), otherwise simply the create() function is called an the object is created.
(Regardless of any violations of the validation rules in $validate)

Why isn't an object also validated in the create method? This behaviour confuses me. By the way, why is the function validate_data() private in the first place? Would be awesome to be able to trigger a validation in it's child classes :)

thank you in advance for your answer

**Comment by cyberscribe** [comment]
Hi Simon,

I wrote to Tom, creator of the plugin, and he says: "A lack of validation before creation is indeed confusing :). I'm not sure why I set it up that way, but I agree with Simon that validation before creation would be a great improvement. It seems like it'd be fine for validate_data() to not be private, too."

So, if you want to work on this on an up-to-date branch and submit a pull request, I will look out for that.

Thanks again.

Best,
Robert
