### ISSUE TITLE
Config folder and main plugin file are not scaffolded

### ISSUE THREAD

**Issue by helarqjsc** [tombenner/wp-mvc#115]
Is it the intended behavior or just a bug?

After I run `wpmvc generate scaffold TestPlugin Test` I get the following folder structure:

    ───app
        ├───controllers
        │   │   tests_controller.php
        │   │
        │   └───admin
        │           admin_tests_controller.php
        │
        ├───models
        │       test.php
        │
        └───views
            ├───admin
            │   └───tests
            │           add.php
            │           edit.php
            │
            └───tests
                    index.php
                    show.php
                    _item.php

Is that normal? Why loader, main plugin file and configs aren't being scaffolded by default? The only way to get the correct working structure is to copy one of the examples, which seems weird and counter-intuitive. Tutorial also doesn't provide much info about it, it says that scaffolding is supposed generate a working plugin, but it doesn't.

**Comment by cyberscribe** [comment]
Using `.wpmvc generate plugin MyPlugin` should create the plugin and loaders as expected. `./wpmvc generate scaffold MyPlugin MyVenue` for example is to add additional models and controllers to an existing plugin. See: http://wpmvc.org/documentation/creating_plugins/#content

Hope that helps!
