### ISSUE TITLE
Possible to nest forms for associations?

### ISSUE THREAD

**Issue by grega** [tombenner/wp-mvc#118]
I'm not sure if I've totally missed something in the docs/source that indicates if this is possible or not; essentially I have a `Club` model, each instance of which `belongs_to` a `Venue`. Rather than have to create each separately and associate the club with the relevant venue using `$this->form->belongs_to_dropdown('Venue', $venues);` within the club admin edit form, I'd like to have a single 'add' form where I can create a club & its associated venue in one go (likewise for the 'edit' form). Is this achievable currently?

**Comment by cyberscribe** [comment]
Hi Greg,

I believe this would be achievable with a custom admin controller that handles the creation of both objects on the back of the posted admin form data in `$this->params`. I hope that helps point you in the right direction!

Best wishes,
Robert

**Comment by grega** [comment]
Great, thanks @cyberscribe!
