### ISSUE TITLE
Feature: Attributes for submit button in admin

### ISSUE THREAD

**Issue by MrTomAsh** [tombenner/wp-mvc#120]
Hello,

please update function end in mvc_form_helper.php. I'm attaching simple version code that allowing to add any attribute to the button (without validation):

```
public function end($label='Submit', $options = null) {
        $attributes = null;
        if($options) foreach($options as $key => $option) {
            $attributes .= "$key=\"$option\"";
        }
        $html = '<div><input type="submit" value="'.$this->esc_attr($label).'" '.$attributes.' /></div>';
        $html .= '</form>';
        return $html;
    }
```

Usage

`<?php echo $this->form->end('Add', array('class' => 'button button-primary customize load-customize hide-if-no-customize')); ?>
`

Cheers!

**Comment by cyberscribe** [comment]
Thanks for the suggestion. Please feel free to submit a pull request with complete, fully-tested code so that we can consider this in context.
