### ISSUE TITLE
Validation not working

### ISSUE THREAD

**Issue by deguto** [tombenner/wp-mvc#124]
Hi,
i tried your events-calendar-example. Any validation e.g. for a new speaker doenst work.

your pattern:
        'first_name' => array(
            'pattern' => '/^[A-Z]/',
            'message' => 'Please enter a capitalized name in the First Name field!'
        ),

but the validation message is not there if you save an spearker with firstname "007". It shows only "No ID specified".

i used wordpress v4.4.2 (currently the newest)
...
I think this is an nice and interesting project if all the basic stuff of MVC is working. :)
thanks.

**Comment by cyberscribe** [comment]
This may have broken in a recent upgrade of either WordPress or the plugin. If you'd like to submit a pull request with a proposed fix, I'd be more than happy to have a look at it. :)
