### ISSUE TITLE
Using models without an association to the current controller/model

### ISSUE THREAD

**Issue by curtisolson** [tombenner/wp-mvc#125]
I want to create an alert for users on a page. The alert has no clear association to the current model/controller, Document.

I first tried this

```
        $this->load_models('Alert','UserAlert');
        $alert = $this->UserAlert->find_one(array(
            'joins' => array(Alert),
            'selects' => array('Alert.message_text'),
            'conditions' => array(
                'UserAlert.user_id' => $current_user->ID
            )        
```
and got this error: 

```
Fatal error:  Call to a member function find_one() on null in [project folder]/wp-content/plugins/sales-tool/app/controllers/documents_controller.php on line 11
```
I figured that $this wasn't associated with UserAlert which is why I was getting null. I then tried this code.

```
        $alert_model = mvc_model('Alert');
        $user_alert_model = mvc_model('UserAlert');
        $alert = $user_alert_model->find_one(array(
            'joins' => array($alert_model),
            'selects' => array('Alert.message_text'),
            'conditions' => array(
                'UserAlert.user_id' => $current_user->ID
            )        
                
        ));
```
And got this error.

```
Cannot use object of type Alert as array in [project folder]/wp-content/plugins/wp-mvc/core/models/mvc_model.php on line 358
```

I want to use the models properly, but my SQL is strong and I'll probably just solve it by re-writing as a SQL query.  Any hints on how to use models the way they are supposed to be used?

**Comment by cyberscribe** [comment]
The controller for that model will have a `$this->Model` you can use. You can also instantiate any models you want as described--either into a class variable or locally. The second error when you did this was because you need to pass a string, not object, to `joins' => array($alert_model)` i.e. `joins' => array('Alert')`.
