### ISSUE TITLE
can i use this in wordpress template?

### ISSUE THREAD

**Issue by hamedmoody** [tombenner/wp-mvc#127]
hi
can i use this in wordpress template?

**Comment by cyberscribe** [comment]
Hi Hamed,

Not really sure what your question is here. This is a plugin that lets you develop other plugins using MVC pattern principles. It is completely independent of any WordPress template or theme.

Best,
Robert

**Comment by neilabdev** [comment]
I have the same question and for me it means, can I render a view using the template I've activated with a standard wordpress installation? I've research Themosis & Lumberjack, all of which seem to require me to modify themes to be compatible (and or manage a separate theme for compatibility). And coming from other frameworks (e.g. rails, grails), I'm just looking to be able to specify a custom route, invokes a controller, then when I render a view its in the current theme selected by wordpress, which the user may change at any time. Is this the right tool for the job? Thx so much!

**Comment by cyberscribe** [comment]
You can use layouts to customise every aspect of a rendered endpoint: http://wpmvc.org/documentation/views/layouts/ - different than a WP theme template but can achieve the same result

**Comment by neilabdev** [comment]
Thx you so much!!! I will do a deep dive into the layout functionality :)
