### ISSUE TITLE
Result of the DB update is not known

### ISSUE THREAD

**Issue by rkoziol7** [tombenner/wp-mvc#128]
It seems that the result of the update of a particular model is not returned to the controller.

My code invokes:
`$this->NewsletterUser->save($this->params['data']);`
returning always true for me - regardless of the record was actually updated or not.

Inside the save function I can see:

```
$this->update($id, $model_data);
$this->update_associations($id, $model_data);
...
return true;
```

So we know nothing about the update's status. I guess the information that $this->update or $this->update_associations finished with some errors is really important.

What do you think?

**Comment by cyberscribe** [comment]
I agree that a hard-coded `return true` is not ideal. Please submit a pull request with the desired behaviour and return values.

**Comment by cyberscribe** [comment]
This is an open issue for which we would gratefully accept a pull request from anyone in the community who wants to improve this bit of the codebase.
