### ISSUE TITLE
Synchronizing models with posts

### ISSUE THREAD

**Issue by waalzer** [tombenner/wp-mvc#133]
According to the documentation I defined a customized custom post type in the model to be able to synchronize posts and models. The post type gets added to the backend and if I create such a post manually everything works as expected. As soon as the post gets synchronized to a model (either by adding a new model object or by adding the post id to an existing model in the database), it loads the corresponding view from the model. So syncing to the model works well.

However the rendered page is not related to an actual WP post anymore. There is no post id given in the HTML, no css classes of the post type are added to the body, the page title set in the post is missing, the menu item is not marked as active and the url also doesn’t match the definition of the post type. The post only seems to forward to the public route of the model (which is the default /controller/id).

Is this an issue or is it just the way synchronizing models with posts is supposed to work in WP MVC?

Thank you!

**Comment by cyberscribe** [comment]
@tombenner do you have a POV on this?

**Comment by tombenner** [comment]
From what I recall, the original intent was to simply sync the model with posts at the data level, and then use the WP MVC-generated public route (`{:controller}/{:id:[\d]+}` by default, as you mention) as the `show` route for those records. The thinking for using WP MVC's routing was that it'd make it easier to add other RESTful routes for that model. So, the behavior you're seeing is the intended behavior.

We might consider supporting WP's native routing for these custom post types. There should only be a single `show` route for any given resource, and I'd lean towards using WP MVC's RESTful, flexible routing over WP's routing as the default, but we could consider supporting opt-in use of WP's native routing instead if there's enough motivation for it. What's your use case, @waalzer?

**Comment by waalzer** [comment]
Thank you @tombenner! In terms of REST this behavior totally makes sense.

We use WP MVC for some of our pages, that are heavily data-driven. Since MVP rendered pages don’t represent a WP post, WordPress doesn’t take care of various things (especially in the HTML header). So at the moment we would need to customize some parts of these pages in order to keep consistency among mvc and non-mvc pages. In our case this means adjusting meta tags, inserting css classes for HTML body and active menu items, manipulating the output of seo plugins (which usually rely on post data as title and excerpt), rewriting urls instead of using the post's permalinks etc.

So native routing would reduce customization and help to keep consistency throughout the website.

**Comment by cyberscribe** [comment]
Anything actionable on this, gents?
