### ISSUE TITLE
Regression in PHP 7.0 - Unable to dynamically access class properties in backend

### ISSUE THREAD

**Issue by grubersjoe** [tombenner/wp-mvc#134]
I'm running PHP v7.0.7 on my development machine and stumbled upon a regression in the core: 

Because "[dereferencing a variable property that is an array has different semantics between PHP 5 and PHP 7](http://php.net/manual/en/language.variables.variable.php)", model properties can no longer be retrieved in `core/helpers/mvc_helper::admin_table_cell` and the fields are not shown in the backend.

[This section](http://php.net/manual/en/migration70.incompatible.php#migration70.incompatible.variable-handling.indirect) in the migration guide explains the new behaviour.

However this issue can be fixed easily by adding curly braces to resolve the ambiguity. I'm sending a PR.

**Comment by cyberscribe** [comment]
Thanks for this!
