### ISSUE TITLE
Save error when custom primary key set

### ISSUE THREAD

**Issue by zatkowich** [tombenner/wp-mvc#137]
Hello,

if I set custom `primary_key` to my model, there is an inconsistency in _mvc_model.php_ method `save()`, line 120:

> `if (!empty($data[$this->name][$this->primary_key])) {`

`$data` that come here have key `'id'` instead of custom primary key name.

I would propose a patch for this quite easily but I don't know whether custom primary key name should come in `$data` or the parameter on the mentioned line should be `'id'` instead of `$this->primary_key`.

Result of this all is that model can't find an object to update in `$data` and continues to `else` branch which means to create a new database record.

**Comment by cyberscribe** [comment]
@tombenner do you have a view on this one?

**Comment by zatkowich** [comment]
I think it happened [here](https://github.com/tombenner/wp-mvc/pull/132/commits/887e226f98ad2f865a9330ba178243536e2fafa6). Maybe it would be a good idea to convert every URL `id` parameter name immediately after parse to belonging custom primary key name and use only this.

**Comment by cyberscribe** [comment]
@tombenner any thoughts?

**Comment by tombenner** [comment]
@zatkowich's idea of using the custom primary key in `$data` makes sense to me. As a user, I'd expect that if I set a custom primary key name, then the name of a parameter in form data for that field would have that custom primary key name instead of `id`.

Do either of you have thoughts about what the preferred approach would be?

**Comment by cyberscribe** [comment]
Hi Tom--that makes sense to me. @zatkowich does that give you what you need to prepare a pull request?

**Comment by haulht** [comment]
Hi, in mvc_admin_controller.php, function create_or_save, i have edit:

> if(!isset($this->params['data'][$this->model->name][$this->model->primary_key]))
>  {
> $this->params['data'][$this->model->name][$this->model->primary_key] = $this->params['data'][$this->model->name]['id'];
> }
>                 if ($this->model->save($this->params['data'])) {
>                     $this->flash('notice', 'Successfully saved!');
>                     $this->refresh();
>                 } else {
>                     $this->flash('error', $this->model->validation_error_html);
>                 }
>             }

And in file core/models/mvc_model.php, i edit function save
> if(isset($model_data['id'])) {
>  unset($model_data['id']);
>             }

**Comment by cyberscribe** [comment]
Thanks, can you send that as a pull request?
