### ISSUE TITLE
Custom routing not working

### ISSUE THREAD

**Issue by haulht** [tombenner/wp-mvc#141]
In routes.php file, i define:
`MvcRouter::public_connect('subsub/{:id:[\d]+}.*', array('controller' => 'subsites', 'action' => 'show'));`

But it doesn't work.
In mvc_public_loader.php, i check **add_rewrite_rules** function and it doesn't work too.

Help me, please!

**Comment by cyberscribe** [comment]
Try instead just:

`MvcRouter::public_connect('subsub/{:id}', array('controller' => 'subsites', 'action' => 'show'));`

or

`MvcRouter::public_connect('subsub/{:id:[\d]+}{:extra:(.*)}', array('controller' => 'subsites', 'action' => 'show'));`

Very similar routes are currently working for me in production here: https://github.com/cyberscribe/tapoetry

**Comment by haulht** [comment]
I want to show subsub/11/blog-1 but it not working

**Comment by cyberscribe** [comment]
Have you tried:

`MvcRouter::public_connect('subsub/{:id:[\d]+}/{:extra:(.*)}', array('controller' => 'subsites', 'action' => 'show'));`

(note the forward slash between the numeric id match and the extra full glob.)

**Comment by cyberscribe** [comment]
Also, did you save permalinks to flush the rewrite rules?
