### ISSUE TITLE
Routing being overridden

### ISSUE THREAD

**Issue by brenodamata** [tombenner/wp-mvc#142]
I know very little about WP-dev and I am building (trying) a plugin that inserts data into a new table and I am using the WP-MVC to control and show these records as I would normally do on any MVC based framework.

In the config/routes.php file I have this set up:

```
MvcRouter::public_connect('{:controller}/{:id:[\d]+}', array('action' => 'show'));
MvcRouter::public_connect('{:controller}', array('action' => 'index'));
```

I have a Recalls _scaffold_. So I have a recall.php inside my models folder, I have a controller for it and the views. When i try to access /recalls or /recalls/1 it redirects me to the WP dashboard.

I installed Monkeyman Rewrite Analyzer to review my routes and I see the routes I need are being overridden.  

Checkout this post on stackexchange for a screenshot: http://wordpress.stackexchange.com/questions/232089/mvc-config-routes-are-being-overridden

**Comment by cyberscribe** [comment]
Have you enabled pretty permalinks? If so, have you saved the permalinks to
flush the rewrite rules cache after adding your routes?

**Comment by brenodamata** [comment]
I've done the former but not the latter. Can you point me to a documentation on how to do this? Thanks.

**Comment by cyberscribe** [comment]
https://wordpress.org/plugins/wp-mvc/faq/

**Comment by brenodamata** [comment]
In the Permalink Settings Common Settings does it matter which option I choose?
I keep getting redirected to the default Hello World page.

**Comment by cyberscribe** [comment]
You need to have an option selected other than "Plain" -- i.e. to have the rewrite rules activated.

https://codex.wordpress.org/Introduction_to_Blogging#Pretty_Permalinks

**Comment by brenodamata** [comment]
Hey @cyberscribe 

Is it possible to set up a route so it uses a slug instead of id?
EG: "/controller/slug"

If so, how does it translate into the router config?
`MvcRouter::public_connect('{:controller}/{:slug}',` array('action' => 'show'));

**Comment by cyberscribe** [comment]
The default route is controller/action where controller is a controller
class name, and action is the method. So, yes--a slug can be used but a
method must be defined for this slug.

**Comment by brenodamata** [comment]
Thank you!

**Comment by cyberscribe** [comment]
What I do for something similar is:

`MvcRouter::public_connect('{:controller}/{:id:[\d]+}{:extra:(.*)}', array('action' => 'show'));`

This would be a URL like:

`books/42-of-mice-and-men`

and the show method for the books controller would search by the id (42) for the book.

see: https://github.com/cyberscribe/tapoetry
