### ISSUE TITLE
Error in Venue Tutorial

### ISSUE THREAD

**Issue by theraz4400** [tombenner/wp-mvc#144]
When following the exact Tutorial as found here: http://wpmvc.org/documentation/tutorial/

I get following Notice and Warning: 

Notice: Array to string conversion in /Applications/MAMP/htdocs/wordpress/wp-content/plugins/wp-mvc/core/helpers/mvc_helper.php on line 193

[MVC] Warning: Undefined property: Venue::Array. 
Thrown on line 193 of /Applications/MAMP/htdocs/wordpress/wp-content/plugins/wp-mvc/core/helpers/mvc_helper.php

![screen shot 2016-07-16 at 11 17 53](https://cloud.githubusercontent.com/assets/20488318/16893926/0eac7b68-4b47-11e6-8c5c-78efb00d286d.png)

**Comment by theraz4400** [comment]
Suggestion: 

change mvc_helper line 195 from: 
`$value = $object->$column['key'];`
to:
```
$key = $column['key'];
$value = $object->$key;
```

**Comment by cyberscribe** [comment]
Thanks! Please submit a pull request.
