### ISSUE TITLE
How to: Search in Public views

### ISSUE THREAD

**Issue by brenodamata** [tombenner/wp-mvc#145]
In the Events example, the search is defined by this variable:
`    var $default_searchable_fields = array('Speaker.first_name', 'Speaker.last_name', 'Venue.name');`

How does one insert a search function in the public views?

**Comment by brenodamata** [comment]
UPDATE:

I set up the `index` function explicit in the public controller and used `$_GET['search']` to get the query from the url. 

I'm trying to access the `MvcDatabaseAdapter` methods but it doesn't return the correct type of object the I can iterate and show clickable links for.

      `$this->db_adapter = new MvcDatabaseAdapter();`

Any ideas?

**Comment by cyberscribe** [comment]
I typically use global $wpdb; for complex queries at this stage. Also you
can use $this->params['search'].

**Comment by brenodamata** [comment]
Does `$this->params['search']` allows for `LIKE` conditions in the query?
Does it return an `MvcModelObject` ?

**Comment by cyberscribe** [comment]
Sorry, $this->params['search'] is the same as $_GET['search'] (assuming the
URL ends in ?search=...)
