### ISSUE TITLE
How do I Add Input Form in a Non-Admin/Public View

### ISSUE THREAD

**Issue by Wayne50** [tombenner/wp-mvc#146]
Trying to add input form in a non-admin/public view without success.  When I attempt the following code: 'echo $this->form->create($this->model->name);'  in a public view I get the following error. 

Fatal error: Call to a member function create() on a non-object 

When I inspect the $this variable in the admin view, which I get no error, I see the Form property within the $this variable when I inspect the $this variable in the public view I do not see the Form property. 

It appears that the Form Property does not get instantiated in the public views, how do i get the form property to instantiate in public views.  

Any and all help is greatly appreciated as this has stumped me the greater part of a week.

Thanks in advance,
Wayne

**Comment by cyberscribe** [comment]
Hi Wayne,

I'm sorry to say that the form generator/processor was never intended for
front-end use. It is only for generating admin forms to manipulate data in
the models.

I do use forms on the front end, but I create these in HTML and process
them with $this->params[].

Hope that helps!

Best,
Robert
