### ISSUE TITLE
Using Slugs in the URL

### ISSUE THREAD

**Issue by brenodamata** [tombenner/wp-mvc#147]
[This issue is a continuation of the thread](https://github.com/tombenner/wp-mvc/issues/142)

A slug is a value from the database. How can there be a method to handle this when the value is unknown? For example, I have a Book controller where instead of calling `books/1` I want to use the book title instead, like `books/of-mice-and-men` to get the show view for that book. What your saying, and correct me if I'm wrong, is that I would need a method with that name to make it work. 
If it were a normal Post from Wordpress, pretty permalinks would handle that, but since I need the MVC plugin to build this custom setup for my "Book" model, I'm at a lost of how to set up this behavior.

I appreciate your time responding to my inquiries.

**Comment by brenodamata** [comment]
UPDATE: I used the `function to_url` described in the [docs](http://wpmvc.org/documentation/routing/pretty_urls.html) and the changed the routing. The created the links with the slug correctly. But it directed to a 404. 
Any thoughts @cyberscribe  @tombenner ?

**Comment by cyberscribe** [comment]
Have you saved permalinks to flush the rewrite rules?

https://wordpress.org/plugins/wp-mvc/faq/
