### ISSUE TITLE
Error when "generate scaffold MyPlugin MyVenu

### ISSUE THREAD

**Issue by hamedmoody** [tombenner/wp-mvc#150]
Hi
this error:
![image](https://cloud.githubusercontent.com/assets/9475089/17353446/f9f7097e-5954-11e6-9925-584bed4c27d5.png)
And this error:
![image](https://cloud.githubusercontent.com/assets/9475089/17353450/083cc73a-5955-11e6-9c9a-f6f8994e0947.png)
occurd.
wp-version: 4.5.3

**Comment by cyberscribe** [comment]
It appears you have not defined the appropriate models and views for Phones. Remember these must be nested under an admin/ sub-folder to work correctly.
