### ISSUE TITLE
Routes, additional paramaters and regular expressions

### ISSUE THREAD

**Issue by freakpants** [tombenner/wp-mvc#151]
I am trying to use more than one parameter per route url. After a few hours of searching/trying i finally figured out that only parameters named "id" and "extra" even work. (Handling for user-defined parameter names would be nice).

I am trying to handle urls of both of these formats:
/de/benutzer/bestellungen/350/
/benutzer/bestellungen/350/ (no language tag)

I finally arrived at the following solution, which after flushing the permalinks, works for both approaches and saves "de" or "" into extra, and 350 into id.
MvcRouter::public_connect('{:extra:[a-zA-Z]+}?[/]?benutzer/bearbeiten', array('controller' => 'users', 'action' => 'edit'));

$mvc_params (another feature that sadly isnt documented anywhere) vardumps the following:
array(4) {
  ["controller"]=>
  string(5) "users"
  ["action"]=>
  string(6) "orders"
  ["id"]=>
  string(3) "350"
  ["extra"]=>
  string(2) "de"
}

i then use 
echo mvc_public_url( array( controller' => $mvc_params['controller'] , 
						'action' => $mvc_params['action'] , 
						'id' => $mvc_params['id'],
						'extra' => $mvc_params['extra'] );
to generate a link to the same page (as soon as it's working, ill replace extra with the language_tag for another language). Unfortunately this results in the following url:

/de?[/]?benutzer/bestellungen/350/

While the regular expression works fine when parsing the permalink, it is returned as verbatim in the mcv_public_url, which it should not.

**Comment by cyberscribe** [comment]
Have you tried enclosing [/] in {} like: {[/]} ? That's my first
thought--though something in the regex patterns should be a clue as to why
the [] are coming back as literal....

**Comment by freakpants** [comment]
Just tried that: 
'{:extra:[a-zA-Z]+}?{[/]}?benutzer/bestellung/{:id:[\d]+}'

Unfortunately this results in a 404 for both
/de/benutzer/bestellung/350/ and
/benutzer/bestellung/350/

**Comment by cyberscribe** [comment]
Have a look at the regex it is doing--maybe you can tail-match as you are giving a glob at the beginning? Also, if you find anything in there that would make core more intuitive, pull requests are gratefully accepted! :)
