### ISSUE TITLE
How do I drop the plugin tables on the uninstall process?

### ISSUE THREAD

**Issue by rsteveyoung** [tombenner/wp-mvc#152]
Is there a function similar to "function activate()" that permits us to place code in order to remove the plugin tables during uninstall process?

`
<?php
function uninstall() {
    ...
    $sql = 'DROP TABLE IF EXISTS '.$wpdb->prefix.'venues)';
    dbDelta($sql);
    ...
}
`

Any help would greatly appreciated.

Thanks in advance,
R. Steve.

**Comment by rsteveyoung** [comment]
Is "function deactivate()" the solution ? because I thought it executes when de plugin is "Deactivated" instead of when it's uninstalled.

**Comment by cyberscribe** [comment]
Indeed, MvcPluginLoader::deactivate() is intended to be called when the
plugin is deactivated. There is no "uninstall" process afaik in WordPress,
just the physical deletion of the plugin files.
