### ISSUE TITLE
Someone had this prob. 3 years ago. Is your plugin still supported?

### ISSUE THREAD

**Issue by swisspenelope** [tombenner/wp-mvc#153]
[MVC] Fatal Error: The attribute "name" was not present when trying to save the post for a Member object. 
Thrown on line 226 of C:\xampp\htdocs\mvc-test\wp-content\plugins\wp-mvc\core\models\mvc_model.php 

But it's not "fatal" because the new Member is created anyway.

Nothing I've tried works and the documentation doesn't go into errors at all.
SP

**Comment by cyberscribe** [comment]
It's an all-volunteer effort, and we're trying to support it as best we can. If you can track that down, catch the error, and handle it more gracefully we'd gladly accept a pull request to make this more intuitive for future users. :)

**Comment by swisspenelope** [comment]
ok ...
