### ISSUE TITLE
get_keyword_conditions() should be documented

### ISSUE THREAD

**Issue by jeffslofish** [tombenner/wp-mvc#156]
I was trying to use LIKE in the conditions of a query, and I stumbled  upon the handy get_keyword_conditions() function which is public but is not documented anywhere in the documentation that I could find.

It would be great to document this so others don't have to browse the wp-mvc source code just to do a LIKE.

**Comment by cyberscribe** [comment]
Thanks @jeffslofish -- we are indeed way behind in documentation. If you'd be interested in working on improving the documentation we can request access for you from @tombenner
