### ISSUE TITLE
Code Generation Fails on Vagrant / Scotchbox

### ISSUE THREAD

**Issue by lorenzo1975** [tombenner/wp-mvc#159]
When trying to run the code generation under Vagrant / Scotchbox fails with Error Establishing Database Connection.
`<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" >
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>Database Error</title>

</head>
<body>
	<h1>Error establishing a database connection</h1>
</body>
</html>`
Based on previous help topic [wp-mvc code generation error](https://wordpress.org/support/topic/cant-run-the-code-generation-utility-wpmvc/)I tried setting db_host as localhost:/run/mysqld/mysqld.sock but no success.

**Comment by cyberscribe** [comment]
This is not related to wp-mvc, but to a misconfiguration of vagrant. The mysql database is not installed and running correctly in Vagrant.

**Comment by lorenzo1975** [comment]
Ok, no big issue I'll work with the plugin on wamp, I can still generate the code and import the plugin. Thanks for quick feedback.

**Comment by cyberscribe** [comment]
Good luck!
