### ISSUE TITLE
Belongs_to relationships not working in AdminController $default_columns

### ISSUE THREAD

**Issue by DODMax** [tombenner/wp-mvc#160]
I'm doing some troubleshooting for a plugin I wrote years ago and it seems that belongs_to relationships are no longer valid in AdminController default_columns (using the default index view).

Any thoughts? Thanks

``` php
class AdminMatchesController extends MvcAdminController
{
    var $default_columns = array(
        'id',
        'season.name' => array('label' => 'Season'),
        'league.name' => array('label' => 'League'),
        'hometeam.name' => array('label' => 'Home Team'),
        'awayteam.name' => array('label' => 'Away Team'),
        'location',
        'start_date' => array('label' => 'Date')
    );
```

`MVC] Warning: Undefined property: Match::season.name. 
Thrown on line 193 of /home/shanghai/www/www/wp-content/plugins/wp-mvc/core/helpers/mvc_helper.php`

**Comment by DODMax** [comment]
Nevermind it seems like it is something I coded myself back then: db2067a599d2e465a330eafba02d67be937280ae

**Comment by cyberscribe** [comment]
Have you tried capitalising the object names in the references (e.g.
Season.name)?

**Comment by DODMax** [comment]
Yep but that's not it. Really the feature just doesn't exist. I guess the approach would be a dedicated admin index view.

**Comment by cyberscribe** [comment]
Feel free to submit a pull request if you feel it would be a useful feature
that could peacefully coexist with the rest of the existing codebase about
relational table associations. :)
