### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function paginate() on null 

### ISSUE THREAD

**Issue by ranjithsiji** [tombenner/wp-mvc#165]
I generated a new plugin using the wp-mvc utility. When I click on the list items on admin screen I am getting an error 

`Fatal error: Uncaught Error: Call to a member function paginate() on null in /var/www/html/schools/wp-content/plugins/wp-mvc/core/controllers/mvc_admin_controller.php:87 Stack trace: #0 /var/www/html/schools/wp-content/plugins/wp-mvc/core/controllers/mvc_admin_controller.php(8): MvcAdminController->set_objects() #1 /var/www/html/schools/wp-content/plugins/wp-mvc/core/mvc_dispatcher.php(58): MvcAdminController->index() #2 /var/www/html/schools/wp-content/plugins/wp-mvc/core/loaders/mvc_admin_loader.php(109) : runtime-created function(1): MvcDispatcher::dispatch(Array) #3 /var/www/html/schools/wp-content/plugins/wp-mvc/core/mvc_dispatcher.php(91): __lambda_func() #4 /var/www/html/schools/wp-includes/class-wp-hook.php(298): MvcDispatcher->__call('admin_schools_i...', Array) #5 /var/www/html/schools/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array) #6 /var/www/html/schools/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #7 /var/www/html/schools/wp-admin/admin.php(222): do_action('toplevel_page_m...' in /var/www/html/schools/wp-content/plugins/wp-mvc/core/controllers/mvc_admin_controller.php on line 87`

On Line 87 

```
public function set_objects() {
        $this->init_default_columns();
        $this->process_params_for_search();
        $collection = $this->model->paginate($this->params);
        $this->set('objects', $collection['objects']);
        $this->set_pagination($collection);
    
    }
```

What is wrong? how to fix ?

**Comment by cyberscribe** [comment]
The default model associated with a same-named controller is `Model` (case-sensitive). Have you tried `$collection = $this->Model->paginate($this->params);`
