### ISSUE TITLE
PHP 7 - extract on mvc_controller tries to reassign $this

### ISSUE THREAD

**Issue by aleextra** [tombenner/wp-mvc#166]
Hi, method MvcController->include_view($path, $view_vars=array()) - $view_vars can contain keys like "this". Exctract function will try to overwrite $this.
line: 255
extract($view_vars);
change to: extract($view_vars, EXTR_PREFIX_ALL, 'view_vars');

That update require to change variable name at views for example from $model to $view_vars_model

Not sure if that is fully compatible with some rest of code, but helps.
Issue exists on PHP 7.

**Comment by Surgeonito** [comment]
Yup, this also occurs while starting with example plugin that's shipped within the package. Doing step by step according to http://wpmvc.org/
PHP 7.1.1
windows machine 
xampp
Fatal error: Uncaught Error: Cannot re-assign $this in ..\wp-content\plugins\wp-mvc\core\controllers\mvc_controller.php:255

**Comment by cyberscribe** [comment]
Thanks, guys. Would welcome a pull request on this.

**Comment by Surgeonito** [comment]
Could you confirm that? 
Are we the very first people that bumped into this problem?
That would be very odd... php7 is not that fresh...

**Comment by cyberscribe** [comment]
I am running wp-mvc derived applications extensively in high-traffic environments using php 7.0.16. I must admit I haven't tried the example plugin out in a long time. :)

**Comment by Surgeonito** [comment]
Yes, but the effect of scaffolding is producing the same Fatal Error.
Again - all done step by step according to documentation.

**Comment by Surgeonito** [comment]
The problematic spot is:
line 33, mvc_dispatcher.php:
`$controller->set('this',` $controller);`

why would you want to do this? what is the purpose of this line?

**Comment by cyberscribe** [comment]
@tombenner will have to respond about the design considerations. I am primarily taking pull requests and looking after the project to make sure it remains viable into the future. Any updates that will help this remain useful for php 7.1x+ gratefully received. :)

**Comment by outcast1000** [comment]
Same problem here with php 7.1.1

**Comment by outcast1000** [comment]
Just made a dirty fix (seems to work)
mvc_controller.php:255
replace
       extract($view_vars);
with
        if (array_key_exists('this', $view_vars)){
            $temp = $view_vars['this'];
            unset($view_vars['this']);
            extract($view_vars);
            $view_vars['this'] = $temp;
        }

**Comment by cyberscribe** [comment]
Thanks @outcast1000 - I just merged in a fix for this. Please see if it is working for you now (from github; hasn't been release to plugin repository yet)

**Comment by cyberscribe** [comment]
@aleextra @Surgeonito - I have merged in your changes, thanks! Please pull from this (master) branch and see if this resolves your issues. I will then push to the Plugin Repository.

**Comment by Surgeonito** [comment]
@cyberscribe splendid! There will be more to come.

**Comment by Surgeonito** [comment]
Though having any info from @tombenner about this line in mvc_dispatcher.php
`$controller->set('this', $controller);`
would be nice. It seems to do something, but can't get the idea.

**Comment by cyberscribe** [comment]
$this:: functions are used extensively in views. I suspect the manner in which the views are rendered (i.e. inside the controller object) means that on older versions of php it was useful to explicitly set() them, whereas now it is forbidden by php7+ to create a $this variable inside a class, as it overrides the self-reference reserved variable. That's all. :)

**Comment by cyberscribe** [comment]
@aleextra @Surgeonito have you had a chance to review the latest merges into the master branch and test? I have tested on my websites and all looks good, but would love to hear from you before I push this to the Plugin Repository for Wordpress.

**Comment by Surgeonito** [comment]
I can confirm - working good.

**Comment by cyberscribe** [comment]
Thanks, guys. I've pushed it to the Plugin Repository.
