### ISSUE TITLE
Routing Does not work

### ISSUE THREAD

**Issue by AlainVandermeersch** [tombenner/wp-mvc#167]
Hello,

I wrote a application with equivalent objects as the events calendar example, But my models are CamelCase( each model name prefixed with my app Acronym 'Cdj' to avoid naming conflicts with other plugins.

Wordpress permalink: Cus/%postname%/%post_id%/tom structure: I tried /%postname%/ and /%postname%/%post_id%/

in my class CdjActivite I added:
function to_url($object) {
            return 'cdj_activites/'.$object->id;
    }
In the debugger the code executes and takes effect on the Resulting url as I changed the return value to see the effect

I added route MvcRouter::public_connect('cdj_activites/{:id:[\d]+}/{:extra:(.*)}', array('controller' => 'cdj_activites', 'action' => 'show')); ( but I believe the predefined Router rules should do it I just did it to make sure.

but with the debugger I see that when I click on the View link from the Wp-Admin Cdj Activites List I
get invariably The requested URL /av-data/cdj_activites/3 was not found on this server. without the controller show method or the show view being invoked as I have breakpoints in the debugger..
av-data is my virtual host under apache
Pls advise I am new to your plugin I like the MVC concept. I can zip you the whole small application if you wish, but you may already have a simple explanation.

**Comment by AlainVandermeersch** [comment]
typo Wordpress permalink: Custom structure: I tried /%postname%/ and /%postname%/%post_id%/

**Comment by AlainVandermeersch** [comment]
[cercledujeudi.zip](https://github.com/tombenner/wp-mvc/files/873232/cercledujeudi.zip)

**Comment by AlainVandermeersch** [comment]
just added zip file of my very small plugin as additional doc

**Comment by cyberscribe** [comment]
Alain--have you tried flushing the rewrite rules by saving permalinks?

**Comment by AlainVandermeersch** [comment]
Hello Robert yes I did without success. I am running this under VirtualBox - Ubuntu 16.04.
My .htaccess file contains # BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /av-data/
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /av-data/index.php [L]
</IfModule>

# END WordPress

And my apache Virtual Directory  says DocumentRoot /var/www/html/av-data

I sense that maybe .htaccess needs to be more explicit than just RewriteRule . /av-data/index.php [L] ?

Many thanks!

**Comment by AlainVandermeersch** [comment]
I installed and tested the events calendar sample and I am hitting the same problem
so I know something is wrong in either setting permalinks/mod_rewrite ( enabled per command
sudo a2enmod rewrite) .htaccess( std wordpress) or ???.
What I noticed are the urls - in the admin part for example to list all Venues:

http://127.0.0.1/av-data/wp-admin/admin.php?page=mvc_venues

To Edit one venue:

http://127.0.0.1/av-data/wp-admin/admin.php?page=mvc_venues-edit&id=1

Works just like my app

http://127.0.0.1/av-data/wp-admin/admin.php?page=mvc_cdj_activites

and to edit
http://127.0.0.1/av-data/wp-admin/admin.php?page=mvc_cdj_activites-edit&id=3

but its the View link that fails both for the events calendar example:
The requested URL /av-data/venues/1/ was not found on this server.

just like for mine:

The requested URL /av-data/cdj_activites/3 was not found on this server.

So its the "Pretty link" PostName that does not seem to apply in the Wp-Admin panels( where a page= url type is applied.

Thanks for looking into this!

**Comment by cyberscribe** [comment]
Alain, I'm sorry to say it sounds like you have configuration issues well beyond the scope of wp-mvc, with your WordPress installation specifically. Unfortunately, that isn't something we can help with here. Good luck!
