### ISSUE TITLE
The fix : "fix error notice in has_many_dropdown" fixes a bug but rise an other

### ISSUE THREAD

**Issue by zeemil** [tombenner/wp-mvc#178]
See commit : 65795b1a721cf76424c31945f3ce32e1b3294c0b

The expression
`isset($this->object->{MvcInflector::tableize($model_name)})`
is always evaluate to false and this fact, the dropdown doesn't show existing relations in the edit admin form.
I use PHP 5.4 and PHP 5.6, I've not tested on a newer version of PHP.

**Comment by cyberscribe** [comment]
Thanks @zeemil -- please can you submit a pull request?
