### ISSUE TITLE
Error in MvcModel::find() method while joining tables in a separate database

### ISSUE THREAD

**Issue by zeemil** [tombenner/wp-mvc#179]
My "wpmvc" tables are in a separated database of wordpress.
I use the `var $database` attribut in all my models.

Let's suppose two models : modA and modB
The relationship is A has many B.
In the A controller, I would like to do a join between this two models :
` $this->model->find( 'joins' => array('B') )`

The query doesn't work because the database prefix is not added before the table name.

I looked in the MvcModel source I don't have the level to determine where is the error.
If any one would have a look, it would be wonderful.

**Comment by cyberscribe** [comment]
Hi @zeemil thanks for this. If you think you have found a bug please submit a pull request.

**Comment by Surgeonito** [comment]
@zeemil do you have relations build properly in you models?
please also - show us the exact code that is causing this kind of problems
