### ISSUE TITLE
Custom Page Template Integration

### ISSUE THREAD

**Issue by realves** [tombenner/wp-mvc#180]
Hi, how can i  integrate my plugin in a custom page template?

**Comment by polcodemichalkrawczyk** [comment]
In two ways.
The fist one is described here https://github.com/tombenner/wp-mvc/blob/master/core/mvc_dispatcher.php#L42-L59

Second by calling creating object with mvc_model() function. That will grant you access to the class and to the data, which you can process as you wish in a page template php file.

**Comment by tucq88** [comment]
@polcodemichalkrawczyk this should be included in README, very nice one
