### ISSUE TITLE
Null model on controller route

### ISSUE THREAD

**Issue by realves** [tombenner/wp-mvc#181]
Hi, i have generated model, view And controller by usino wpmcv command Line tool.

In The controller using $this->Model->find() method i getto fatal error: Call To A member function find() on null in ...

Where is The fault?

**Comment by realves** [comment]
```
public function show() {

		$users_model = mvc_model('Users');

		$object = $users_model->find_by_ID($this->params['id_user']);
        
        if (!empty($object)) {
            $this->set('data', $object);
        }else{
			$this->set('data', $this->params);
		}
    }
```

This works! But `$this->model` is always null... when  can(/do) i use `$this->model->{method}` ?

**Comment by nhatnx** [comment]
Model name must be in singular form. Your model name and file must be "User" and "user.php".
