### ISSUE TITLE
No need to create table when create new model

### ISSUE THREAD

**Issue by nhatnx** [tombenner/wp-mvc#189]
Hi,

I created a new wpmvc plugin only used to create, read, update and delete records with a specify post_type. I mean I only use my new wpmvc plugin to CRUD records which have post_type='my_post_type' on wp_posts table. So I don't need to create a new table for the new wpmvc model.

Could you guide me how to create a plugin like that?

Thank you for your help.

Nhat Nguyen (Mr.)

**Comment by cyberscribe** [comment]
Hi Nhat,

wp-mvc isn't really designed to deal with custom post types; it's an after-thought to the main purpose, which is CRUD on a *new* table using MVC. So, for a custom post type CRUD (only) you will want to use a [different plugin](https://wordpress.org/plugins/search/custom+post+type/).

Best,
Robert
