### ISSUE TITLE
php fatal error on generate a plugin

### ISSUE THREAD

**Issue by media-store-net** [tombenner/wp-mvc#194]
Hi, when i try to generate a plugin, i get an php error like this

> PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in C:\MAMP\htdocs\wp\wp-includes\wp-db.php:1633

I use a windows machine with git bash, php-version is 7.1.0 , global path, WP-Version is the latest 4.8.3.
I know that the mysql is out of date and should using a mysqli connection. But why the script / wp-db use a mysql connection?

I'm looking the problem on issues. but nothing found.

what is wrong?

**Comment by cyberscribe** [comment]
This is indeed a problem with mysql in WordPress. Whenever a model is generated in wp-mvc, the plugin queries the schema of the model to make sure it lines up. Without mysql working, WordPress itself won't work at all. And neither will any wp-mvc plugin.
