### ISSUE TITLE
Migrate from V1.2 to 1.3.11 MvcRouter::ajax_connect

### ISSUE THREAD

**Issue by nomadinteractif** [tombenner/wp-mvc#195]
Hello,

I need to update your plugin on my client website from V1.2 to the current version.  
Since, I did not build the website, I'am not sure what this code has an impact on.
`
MvcRouter::ajax_connect( array( 'controller' => 'probes', 'action' => 'find' ) );
MvcRouter::ajax_connect( array( 'controller' => 'probes', 'action' => 'get' ) );
MvcRouter::ajax_connect( array( 'controller' => 'probes', 'action' => 'getModelsParameters' ) );
MvcRouter::admin_ajax_connect( array( 'controller' => 'probes', 'action' => 'find' ) );
MvcRouter::admin_ajax_connect( array( 'controller' => 'probes', 'action' => 'get' ) );
MvcRouter::admin_ajax_connect( array( 'controller' => 'probes', 'action' => 'getModelsParameters' ) );
`
The method `MvcRouter::ajax_connect` has been deprecated since the version 1.2 and generate a Fatal Error.  From what I think, I could just remove the 3 lines with MvcRouter::ajax_connect and the 3 others with `MvcRouter::admin_ajax_connect` will take care of the routing.  I'am I right ?  Otherwise, what should I do?

Thank you

Jasson

**Comment by polcodemichalkrawczyk** [comment]
Instead of 
`MvcRouter::ajax_connect( array( 'controller' => 'probes', 'action' => 'find' ) );`
use
`MvcRouter::public_connect( array( 'controller' => 'probes', 'action' => 'find' ) );`

I think that will do the job.

**Comment by cyberscribe** [comment]
Great, thanks. If something is required in the code, please submit a pull
request!

On 19 January 2018 at 12:30, polcodemichalkrawczyk <notifications@github.com

**Comment by nomadinteractif** [comment]
Great ! Thank you !
