### ISSUE TITLE
Model's $in_menu = false still shows the model in the Admin Menu

### ISSUE THREAD

**Issue by mysti9uemirage** [tombenner/wp-mvc#201]
I do not want the add/edit/delete functionalities to show up in the Admin menu. 
I understood from http://wpmvc.org/documentation/models/model_attributes/  that I needed to use var $hide_menu = false;, which is deprecated, and so I did var $in_menu = false; 
However, my model is still showing up in the admin menu.
Can you explain if this is a bug or am I not understanding something?

**Comment by cyberscribe** [comment]
var $in_menu = false should work if it's in the model class scope.

You can also further customise which options show up and how with:

MvcConfiguration::append(array(
  'AdminPages' => array(
    'model_name' => array( 'add' => array('label' => 'custom_label'),
'edit', 'delete', 'parent_slug' => 'whatever.php');

in boostrap.php

**Comment by mysti9uemirage** [comment]
Thank you, the second part helped me figure out a work-around for the problem. I believe that there's a bug, but I don't know how to fix it yet. Please see this for the video explaining what I'm seeing: https://youtu.be/9w0_rQg2GvM

The work-around is adding bootstrap.php under config folder and using this code:
MvcConfiguration::append(array(
	'AdminPages' => array(
		'qr_states' => array('hide_menu' => 'true')
		)
	));

Another side question: I believe I will be using this library a lot. Is there any way I can pay to get tutoring to understand the architecture and get help on an as-needed basis so that I can understand the code more, so I can fix the library if I see a bug, etc.? We can start a private conversation if possible.

**Comment by cyberscribe** [comment]
Thanks @mysti9uemirage for your comments. I use the library a lot as well, and find it very useful. Tutorials on MVC and the website: http://wpmvc.org/ are a good starting place. I'm not available for ongoing support with this right now, but others on this github thread might take you up on this. Happy MVC'ing!

**Comment by mysti9uemirage** [comment]
@cyberscribe : I would like to understand why this is closed even though I believe that there's an unfixed, existing bug? I don't know how to fix it myself. The details are in previous comment (namely, the questions I raised in the video describing the bug). If you can give me some pointers, I can try to fix it myself. I do not think it's right to close when the bug is present though, or the documentation should be updated.

**Comment by mysti9uemirage** [comment]
Hi,

No, hide_menu is depreciated. When used it, there are explicit code to throw the following error (this shows that the documentation is outdated, as mentioned in my previous posts):
   `[MVC] Fatal Error: The 'hide_menu' attribute (in the QrState model) should be defined as 'in_menu' in 'AdminPages' in MvcConfiguration as of WP MVC 1.2 (read more). 
Thrown on line 28 of C:\xampp\apps\summit\htdocs\wp-content\plugins\wp-mvc\core\models\mvc_model.php`

I've looked at your plugin. There's no code using in_menu/hide_menu. It's only using show_in_menu. Upon activation, it looks like the MVC framework is trying to add your models to the admin's menu bar but received the following errors instead:

   
[summit-interactive.zip](https://github.com/tombenner/wp-mvc/files/1628905/summit-interactive.zip)
[summit-interactive.zip](https://github.com/tombenner/wp-mvc/files/1628906/summit-interactive.zip)

`[MVC] Warning: The schema for Partner is empty. It's likely that the plugin generating this table isn't working, or you may need to deactivate and activate it. Please make sure that the table "wp_partners" exists. 
Thrown on line 60 of C:\xampp\apps\summit\htdocs\wp-content\plugins\wp-mvc\core\models\mvc_model.php 
... `

===

I'm attaching my plugin for your reference. Qr State model should not show up in the admin's side menu, while Qr Screens Info should. You'll need to go to models\qr_state.php to change hide_menu to in_menu. I'm suspicious that your MVC framework code base is not the same as what I have (I just have the latest one from the repository)

**Comment by cyberscribe** [comment]
Thanks for this. If neither in_menu or hide_menu are working as expected, a pull request would be gratefully received. If you're interested in updating documentation as well, we could speak with Tom (the creator). Thanks again!

**Comment by mysti9uemirage** [comment]
Yes, I would do a pull request and fix it if I have an idea of what I need to do to fix it. I don't right now. My major impediments are as outlined in the video link I previously posted: https://youtu.be/9w0_rQg2GvM

**Comment by cyberscribe** [comment]
Hi,

Thanks for your interest.

I am not the plugin author, so to find where to go would probably take me
as much time as it would you, in which case I should just fix it myself.
It's not a high priority, since there's a good workaround, but if you are
willing to spend the time to figure out how to help, a pull request is
always welcome.

Thanks again!

-R
