### ISSUE TITLE
Recommended way to return a JSON

### ISSUE THREAD

**Issue by ivamluz** [tombenner/wp-mvc#204]
In case I create an action that returns either HTML or JSON (depending on the content-type header), is there a recommended way to return JSON content?

Should I create a view that is responsible for encoding the data as JSON or is there any method in the controller that can be called directly to return JSON, instead of setting a parameter in the view?

**Comment by cyberscribe** [comment]
I do this all the time. I do it in the controller. I just send a json
content type header, echo a json_encode of an array or object, and add a
die statement to prevent the view rendering.

You can switch on a $param (get line) or anything else you want to
determine json output.

HTH!

**Comment by secretcoder** [comment]
@cyberscribe How to you set the content type header? Having no luck on setting it.

**Comment by cyberscribe** [comment]
`
header('Content-type: application/json');
echo json_encode([]);
die();
`

**Comment by secretcoder** [comment]
@cyberscribe Very nice framework, I will use it to implement a Product Catalog CMS. Thank you.
