### ISSUE TITLE
Failed to generate plugin

### ISSUE THREAD

**Issue by mkerbouche** [tombenner/wp-mvc#211]
Hi! 

When a I try to generate plugin following the tuto I have this issue : 

$ ./wpmvc generate myplugin                               
./core/                                                                                                      
<br />                                                                                                       
<b>Parse error</b>:  syntax error, unexpected T_STRING in <b>****/wp-includes/l
oad.php</b> on line <b>1095</b><br />  

I'm on Wordpress 4.9.4 and I've tried with php 5.4 and php 7.1

Thanks  !

**Comment by cyberscribe** [comment]
Hi--this doesn't look related to the plugin. Line 1095 is:

`return ( $thing instanceof WP_Error );`

But it seems like there is a parse error there in your installation (i.e. that line says something else that isn't valid PHP). You may want to reinstall WordPress, disable other plugins, and debug from there.

**Comment by mkerbouche** [comment]
The wordpress installation is new, it's a clean install there is no plugin...

**Comment by cyberscribe** [comment]
Looks like the correct syntax is: `./wpmvc generate plugin MyPlugin`. If that doesn't work, is this a multisite installation?

**Comment by mkerbouche** [comment]
It's the same : 

$ ./wpmvc generate plugin myplugin                        
<br />                                                                                                       
<b>Parse error</b>:  syntax error, unexpected T_STRING in <b>/homepages/12/d563432393/htdocs/bf/wp-includes/l
oad.php</b> on line <b>1095</b><br />

**Comment by cyberscribe** [comment]
Thanks.

Can anyone else watching this thread reproduce this? So far no luck for me...

**Comment by cyberscribe** [comment]
Also what is the text on `/homepages/12/d563432393/htdocs/bf/wp-includes/load.php` line 1095?

**Comment by mkerbouche** [comment]
it is : return ( $thing instanceof WP_Error );

**Comment by cyberscribe** [comment]
Unfortunately on a clean installation of WordPress (single site) with just the wp-mvc plugin, I cannot reproduce this:

```
$ ./wpmvc generate plugin myplugin MyPlugin

Welcome to WP MVC Console!


[Running Generate::plugin]

[Complete]

$ ls ..
akismet		hello.php	index.php	myplugin	wp-mvc
```

**Comment by cyberscribe** [comment]
This is running `PHP 7.0.27 (cli) (built: Jan  5 2018 12:26:39) ( NTS )` WordPress 4.9.4 and WP MVC 1.3.14 (latest) from the plugin repository.

**Comment by cyberscribe** [comment]
Silly question: have you _activated_ the plugin on the install already?

**Comment by mkerbouche** [comment]
Yes it is activated.

**Comment by mkerbouche** [comment]
I've tried on several installations of WP but it always failed

**Comment by mkerbouche** [comment]
I've found the issue : 

https://assistance.1and1.fr/hebergement-c65619/programmation-c65626/php-c65653/php-cli--executer-des-scripts-dans-le-shell-a793786.html

I am hosted by 1and1 and they provide an old version of php when using command line. 

I had to specify the version of php when using the command line

**Comment by cyberscribe** [comment]
Great, glad you found it!

In case anyone else finds this thread in future, could you specify which version of php was the culprit? Sounds like it wasn't able to parse the `instanceof` command? Or something else?

Thanks for coming back to clarify.
