### ISSUE TITLE
Function create_function() is deprecated in php 7.2.0

### ISSUE THREAD

**Issue by learnercys** [tombenner/wp-mvc#212]
Using `wp-mvc` with wordpress@4.9.4 and php@7.2.0 give the error: 

```
Deprecated: Function create_function() is deprecated in .../wp-content/plugins/wp-mvc/core/loaders/mvc_admin_loader.php on line 140
```

**Comment by cyberscribe** [comment]
Thanks. If you'd like to refactor this to use[ anonymous](http://php.net/manual/en/functions.anonymous.php#example-164) (lambda) functions instead, we'd welcome a pull request.

**Comment by learnercys** [comment]
I would like to do that, but unfortunately I'm not sure when since since I don't have to much time right now.
