### ISSUE TITLE
Differences between public and admin controllers

### ISSUE THREAD

**Issue by learnercys** [tombenner/wp-mvc#213]
I was looking the controllers' docs and [here](http://wpmvc.org/documentation/controllers/), and it says that there're two types of controllers but I couldn't figure out what's the differences between both types.

**Comment by learnercys** [comment]
Forget it, I think I got it, it seems that in any model the admin controllers is the one who have access to edit and create methods, and the other one  only have access to the show method, right?

**Comment by cyberscribe** [comment]
Admin controllers govern the admin endpoints; public controllers govern the
publicly-viewable endpoints (i.e. not under the admin area of WordPress).
HTH!
