### ISSUE TITLE
Ajax example for update tree

### ISSUE THREAD

**Issue by learnercys** [tombenner/wp-mvc#215]
Any example using [update_tree](https://github.com/tombenner/hierarchical-documentation/blob/master/app/controllers/admin/admin_documentation_nodes_controller.php#L53) endpoint with jquery? 

So I created an endpoint like this: 

```
MvcRouter::admin_ajax_connect(array('controller' => 'admin_questions', 'action' => 'save_ajx'));
```
and its `save_ajx` method, now I don't know how the jquery request should look like, I have this:

```
jQuery.post('<?php echo mvc_admin_url(array('controller' => 'admin_questions', 'action' => 'save_ajx')); ?>', function() {
    console.log('success')
});
```

but it's not doing what I think it should, any help ? :)

**Comment by cyberscribe** [comment]
Sounds like you found your answer? If so could you post in case anyone else comes looking here? :)
