### ISSUE TITLE
Routing not working after upgrade

### ISSUE THREAD

**Issue by fkh000** [tombenner/wp-mvc#223]
Hi,
after a long time I upgraded one of my projects and seems like the routing stopped working. 

My routes.php:
$albums = array('galeria', 'vystavy');

foreach($albums as $album) {
    MvcRouter::public_connect($album, array('controller' => 'galleries', 'action' => 'show', 'album' => $album));
    MvcRouter::public_connect($album . '/{:id}', array('controller' => 'galleries', 'action' => 'show', 'album' => $album));
}

Example URL:
galeria/2018/

I expect these parameters passed to controller:
`array(4) { ["controller"]=> string(9) "galleries" ["action"]=> string(4) "show" ["id"]=> string(4) "2018" ["album"]=>"galeria" }`

But instead I get only this. It is basically right, just missing the 'album' parameter.
`array(3) { ["controller"]=> string(9) "galleries" ["action"]=> string(4) "show" ["id"]=> string(4) "2018" }`

Used to work in older version (not sure which was that). Is there some other way to pass variables from route to controller?

PS. I refreshed the permalinks.

**Comment by cyberscribe** [comment]
Hi,

controller, action, and id are the only parameters currently accepted. I
believe there is also an undocumented "extra" parameter you can use. But
there is no "album" parameter that I know about. See:
http://wpmvc.org/documentation/routing/

Perhaps you were handling this another way?

**Comment by fkh000** [comment]
Thanks for answer.

In older versions, the 'album' parameter, which was my own, was passed to
controller/action as a parameter when used in the manner I wrote in topic.
I am not sure how I found this out, because it is not mentioned enywhere in
docs. Probably I just accidentally abused a bug, which has been fixed in
newer versions.

I had to fix it by creating separate controller actions. Would be nice to
be able to send custom parameters to the controller.

$albums = array('galeria', 'vystavy');

foreach($albums as $album) {
    MvcRouter::public_connect($album, array('controller' => 'galleries',
'action' => 'show_' . $album));
    MvcRouter::public_connect($album . '/{:id}', array('controller' =>
'galleries', 'action' => 'show_' . $album));
}



2018-05-30 11:48 GMT+02:00 Robert Peake <notifications@github.com>:

> Hi,
>
> controller, action, and id are the only parameters currently accepted. I
> believe there is also an undocumented "extra" parameter you can use. But
> there is no "album" parameter that I know about. See:
> http://wpmvc.org/documentation/routing/
>
> Perhaps you were handling this another way?
>

**Comment by cyberscribe** [comment]
If you'd like to work on allowing any parameters in the routing pattern in
a way that is backwards-compatible, we would welcome a pull request.

**Comment by fkh000** [comment]
Srry, too much work for me, done it the proper way now and hopefully i am
done with it for couple more years :)

2018-06-04 10:08 GMT+02:00 Robert Peake <notifications@github.com>:

> If you'd like to work on allowing any parameters in the routing pattern in
> a way that is backwards-compatible, we would welcome a pull request.
>
>
