### ISSUE TITLE
"After actions" don't run when I use render_view in an action of a controller

### ISSUE THREAD

**Issue by nhatnx** [tombenner/wp-mvc#230]
I want to use custom layout in an action of a controller, so I use render_view in it. But if I use render_view, "after actions" won't be executed.
I find that you use "die()" in render_view function in mvc_controller.php. I think it prevents "after actions" from continuing running.

**Comment by cyberscribe** [comment]
After the view is rendered, the execution is complete. I'm not sure what
you mean by "after actions". The only such things I know about are in
models, not controllers or views (e.g. "after find").

**Comment by nhatnx** [comment]
I mean this one http://wpmvc.org/documentation/controllers/controller_attributes/after.html

If you have an action with **$this->render_view(...)** in it, "after" methods won't be executed. E.g. **set_venues()** in above link.

**Comment by cyberscribe** [comment]
This will run before the view is rendered.

**Comment by nhatnx** [comment]
No. You can try:

<?php
class EventsController extends MvcPublicController {

  var $after = array('set_venues');
  
  public function set_venues() {
    $this->load_model('Venue');
    $venues = $this->Venue->find();
    $this->set('venues', $venues);
  }

  public function some_action() {
    $this->render_view('show', array('layout' => 'custom_layout'));
  }
  
}
?>

Then you call **events/some_action/**
**set_venues()** won't be reached.

**Comment by cyberscribe** [comment]
Ah, right. It only gets fired I guess if you let the controller "fall
through" to the view of the same name; not if you explicitly call
render_view.

If you think this is a bug, we would welcome a pull request:
https://github.com/tombenner/wp-mvc

**Comment by nhatnx** [comment]
But how can I use custom layout without using **render_view()** in controller?

**Comment by cyberscribe** [comment]
You can't.

But you can just call:

$this->set_venues()
$this->render_view(...

in any controller endpoint where you want that function to execute before
rendering the view.

**Comment by nhatnx** [comment]
Ah, I would like to do something more (not only set_venues()) after rendering the view with custom layout 😄

**Comment by cyberscribe** [comment]
Ah, right.

Well, the controller context is available to you in the view ($this), so
you should be able to trigger additional code at the bottom of the layout
if desired.

Again, if you see a better structure or approach here, feel free to submit
a pull request.

Good luck!
