### ISSUE TITLE
This is creating an error, probably use this instead? $html .= $this->select_tag('data['.$this->model_name.']['.$field_name.']', $options);

### ISSUE THREAD

**Issue by gilbertk88** [tombenner/wp-mvc#231]
https://github.com/tombenner/wp-mvc/blob/abeb610140911721f1e1eae0d3c3c53bd5535ed0/core/helpers/mvc_form_helper.php#L214

**Comment by cyberscribe** [comment]
Thanks. Can you make sure we have `isset()` checks in place for this and we can merge in the pull request?
