### ISSUE TITLE
Error establishing a database connection

### ISSUE THREAD

**Issue by Brandon300055** [tombenner/wp-mvc#236]
when I run
 ./wpmvc generate plugin test
I get this error

(base) admins-MacBook-Pro-2:wp-mvc admin$ ./wpmvc generate plugin test
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>Database Error</title>

</head>
<body>
	<h1>Error establishing a database connection</h1>
</body>
</html>

**Comment by cyberscribe** [comment]
This indicates a problem with your WordPress setup, not this plugin specifically.
