### ISSUE TITLE
Question: Connect WC_Product with a model

### ISSUE THREAD

**Issue by Konafets** [tombenner/wp-mvc#243]
Hi,

is it possible to connect a third-party custom post type like `product` with an MVC model? Can I just do this as it has been done for the default WP models (https://github.com/tombenner/wp-mvc/blob/master/core/models/wp_models/mvc_user.php)?

**Comment by cyberscribe** [comment]
There is no automatic connection; you would have to maintain this relationship yourself using either a join table or a post ID in the mvc table.

**Comment by Konafets** [comment]
Maybe I did not explain it very well. I didn't mean a relationship. I like to do something like:
`$this->Product->find()`

The underlying question I have here is: How can my MVC models interact with the WooCommerce (or any other third-party) models?

**Comment by cyberscribe** [comment]
You would need to maintain those interactions manually. MVC models are one-to-one (active record pattern) relationships to a single (new) table that you create; Products are a post type stored in the posts table.
