### ISSUE TITLE
Add language to url

### ISSUE THREAD

**Issue by jafamo** [tombenner/wp-mvc#248]
Hi,
I created a new plugin on wordpress 5.0 with MVC plugin.

My plugin is working properly in http://localhost/xxxx/pluginName/
On my controller I have this:
```
     $myLocale = get_locale();
        if(strcmp($myLocale,'en')===0){
                $myLocale = 'en_US';
        }else if(strcmp($myLocale,'es')===0){
                $myLocale = 'es_ES';
        }else{
                $myLocale = 'it_IT';
        }

.....

$this->render_view('testFolder/viewTest');

```

I would like to know how to do working url with languages.

Example: 
http://localhost/xxxx/es/pluginName/
http://localhost/xxxx/en/pluginName/
http://localhost/xxxx/it/pluginName/

Regards,

**Comment by cyberscribe** [comment]
You can accomplish this in the plugin by passing a ?lang= (or similar) parameter on the URL, or what I do is set up a multisite instance with sub-sites corresponding to the languages, and activate the plugin globally on the multisite instance. That way everything within e.g. .../it/ is in Italian, including all site-wide string translations. Good luck!
