### ISSUE TITLE
This plugin has been closed as of April 2, 2020 and is not available for download. Reason: Security Issue.

### ISSUE THREAD

**Issue by celorodovalho** [tombenner/wp-mvc#253]
This plugin has been closed as of April 2, 2020 and is not available for download. Reason: Security Issue.

There're no intentions to get it working again?

**Comment by cyberscribe** [comment]
It isn't actually broken and there are no real security problems; the WP repo maintainers made up some reasons to get it out of the repo. because they don't want any frameworks for WordPress in the repo anymore. So, we are supporting it here on GitHub.

**Comment by celorodovalho** [comment]
@cyberscribe 
Ok, thanks for letting me know, I was not aware of it.

I used to use your repo with composer wpackagist, but is not possible to use it from there anymore.
There's a way to use it with composer now?

**Comment by celorodovalho** [comment]
@cyberscribe @tombenner 

Can you help me with that please?

```
    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "tombenner/wp-mvc",
                "version": "1.5",
                "source": {
                    "url": "https://github.com/tombenner/wp-mvc.git",
                    "type": "git",
                    "reference": "origin/master"
                }
            }
        }
    ],
    "require": {
        "tombenner/wp-mvc": "1.5"
    },
```

There's no way to make it work, I tried all possible ways.
```
tombenner/wp-mvc 1.5 -> could not be found in any version, there may be a typo in the package name.
```

**Comment by cyberscribe** [comment]
Sorry, I wasn't even aware this was a composer package...
