### ISSUE TITLE
[MVC] Warning: Undefined property: City::id. 

### ISSUE THREAD

**Issue by prabhuchelladurai** [tombenner/wp-mvc#44]
[MVC] Warning: Undefined property: City::name.
Thrown on line 192 of /var/www/html/wordpress/wp-content/plugins/wp-mvc/core/helpers/mvc_helper.php 

I get this message when i view the plugin main menu in the side bar. 

How to recover from it and what is the possible cause of this error?
and whenever i try to add a record i get the following message:

Add City

[MVC] Fatal Error: Field "code" not found for use in a form input.
Thrown on line 5 of /var/www/html/wordpress/wp-content/plugins/cities-world/app/views/admin/cities/add.php

please guide me in this regard..
Thankyou.

Prabhu.

![screenshot from 2014-11-03 16 41 08](https://cloud.githubusercontent.com/assets/9210333/4881541/43d05a44-634a-11e4-9450-b59426eb1b39.png)
![screenshot from 2014-11-03 16 41 39](https://cloud.githubusercontent.com/assets/9210333/4881542/43dabed0-634a-11e4-9a9d-349b490452ea.png)

**Comment by franklinvvidal** [comment]
Be careful with the name of database table and the name of scaffold of these table for pluralization. For example, in the intro tutorial  [http://wpmvc.org/documentation/tutorial/](url), a table has the name `prefix_venues` and the scaffolding command `./wpmvc generate scaffold VenueListing Venue`( Venue in singular).
This help me a lot and solve my problem.

**Comment by cyberscribe** [comment]
Thanks, it's a good tip. Let me know if you have interest in revising the documentation.

**Comment by franklinvvidal** [comment]
Yes, i have interest.

**Comment by cyberscribe** [comment]
@tombenner thoughts on granting access to @franklinvvidal to update the documentation?

**Comment by tombenner** [comment]
@cyberscribe Sure! I've added @franklinvvidal as a collaborator on `wp-mvc-doc`. @franklinvvidal, let us know if you have any questions!
