### ISSUE TITLE
Help Needed for Customizing Admin Menu and Submenus

### ISSUE THREAD

**Issue by aaroncymor** [tombenner/wp-mvc#56]
Hi there,

Good Day!

I'm seeking for anyone here who can assist me with with WP MVC. I'm trying to customize admin menus and submenus for my plugin. I noticed that every time a controller is created, it creates a menu and submenu for its index which actually has the same name. I want to remove the submenu that has the same name with the top level menu one. I tried configuring that via bootstrap.php, but I'm having a hard time trying to remove that. Any workaround would do as well..

![image](https://cloud.githubusercontent.com/assets/594238/6723216/8c3c9960-ce1f-11e4-85bf-c06b5750567c.png)

Thank you!

**Comment by prabhuchelladurai** [comment]
Hey, you have solution. Follow the link i have provided here, in which you can find many answers as well as mine.

Good time...

Prabhu...

http://wordpress.stackexchange.com/questions/136058/how-to-remove-admin-menu-pages-inserted-by-plugins/170205#170205

**Comment by aaroncymor** [comment]
Hi Prabhu,

Thanks for sharing a solution and for your help. I saw that a few days ago although I can't remember if I tried that already. I will let you know. 

Regards,
Aaron Cymor
