### ISSUE TITLE
WP-MVC is not suitable for high-traffic websites

### ISSUE THREAD

**Issue by cyberscribe** [tombenner/wp-mvc#57]
I have been using this framework as the basis for numerous custom plugins on a high-traffic website and have discovered a bug. Basically, WP-MVC reloads the rewrite rules on every page load, which physically removes and re-adds them from the database with each load. This is warned against in the latest version of the Wordpress documentation as a very bad idea: http://codex.wordpress.org/Function_Reference/flush_rewrite_rules . It means that under high-concurrency traffic spikes, this can result in routes being momentarily unavailable at time of page load, resulting in intermittent 404 errors. In my testing of high-concurrency, this could spike up to 10% of the time, (ab -n 100 -c 10) and has been very difficult and frustrating to diagnose due to the intermittent nature of the problem. My current pull request: https://github.com/tombenner/wp-mvc/pull/42 addresses this issue. If anyone knows how to reach Tom Benner (I have been trying repeatedly) please let me know, since as it is now the WP-MVC framework from his master branch is not suitable for high-traffic websites. It is otherwise a really great framework, and I would love to see it become concurrency-safe on the master branch.

**Comment by aaroncymor** [comment]
Hi @cyberscribe, thanks for continuous support for wpmvc. I'm currently using this plugin for our project and had just found out that there were no updates for this plug-in for 2 years. Luckily, it still works with the most updated version of wordpress. But it would be indeed better if you were to continue support for this plugin and update it. As much as I want to contribute, my knowledge with wordpress, and PHP itself is limited. However, I would love to help you contact Tom Benner regarding this. By any chance, have you tried reaching him via e-mail (tombenner@gmail.com)? He had also provided a list on how we could reach him on his site (http://tombenner.co/). By the way, I'm not related to him, just wanted to provide my support for this plugin :)

**Comment by cyberscribe** [comment]
Hi -- thanks for your enthusiasm for the plugin. I think it's a great idea too, which is why I have reached out to Tom a couple if times at his Gmail and even did a trial of LinkedIn Premium so I could DM him there. Nothing back yet but open to all suggestions. My fork does work for high traffic but there is a caveat that if you rebuild perms links you'll have to deactivate/re activate the plugin to get your routes back. Would love to collaborate with Tom on a permanent solution to keep this framework maintained.

**Comment by aaroncymor** [comment]
Dear @tombenner 

Good Day!

I would like to seek help from you with regards to WP MVC. As per previous comments above, I would like to know if @cyberscribe could help in assisting the plugin's updates? This would benefit developers like us - especially to those beginners that are having a hard time developing a WP plugin using current WP library. I'm currently using WP MVC for our project as I was able to easily understand/grasp the flow of this framework due to familiarity with MVC and to your documentation.It only took me less than a month to finish this provided that I have basic knowledge in Wordpress and PHP. Probably the only remaining issue is the compatibility of the plugin with the current version of wordpress, and its upcoming updates.

Hoping this letter would reach you. It would be an honor to see updates to this plugins again.

Sincerely,
Aaron

**Comment by samwilson** [comment]
What is the status of this plugin now? It looks like this repo is being maintained now (mainly by @cyberscribe?). That's great news!

**Comment by cyberscribe** [comment]
Hi Sam,

Tom and I are working together. The release of wp-mvc 1.3 has been tested
with Wordpress 4.2 and includes a number of bug fixes that make it more
suitable for production use on high-traffic websites. The new version
should be released into the plugin repository soon.

Thanks for your support of wp-mvc.

Best wishes,
Robert

**Comment by aaroncymor** [comment]
Wow! This is good news! I can't wait to test the updated plugin. Definitely looking forward to that since support for this has been revived. I will recommend this to my fellow developers as well. Thank you all your help, @tombenner and @cyberscribe! Have a great day ahead!

**Comment by samwilson** [comment]
Yes, this is terrific! Thanks for the update. :-)

**Comment by kim07** [comment]
healthy dissolution for me :)

**Comment by cyberscribe** [comment]
wp-mvc is back in action!
