### ISSUE TITLE
Strict standards: Non-static method MvcRouter::admin_page_param() should not be called statically

### ISSUE THREAD

**Issue by virticchio** [tombenner/wp-mvc#64]
Hi!
I report the following problem:
Strict standards: Non-static method MvcRouter::admin_page_param() should not be called statically, assuming $this from incompatible context ....

Description problem:
at line 7 of file "root_directory/wp-content/plugins/wp-mvc/core/pluggable/views/admin/index.php", a call is made to the method "admin_page_param" of that class "MvcRouter". The method "admin_page_param" of the class "MvcRouter" instead is declared as no static.

**Comment by cyberscribe** [comment]
Thanks, we'll take a look at this.

**Comment by cyberscribe** [comment]
Simple fix; we have made this static again. Thanks for reporting it!
