### ISSUE TITLE
How to force reload rewrite rules during dev?

### ISSUE THREAD

**Issue by amarcadet** [tombenner/wp-mvc#67]
It seems like adding new routes in `routes.php` only takes effect after deactive / active the plugin.

During development, it's quite annoying, is there a workaround to force a reload of the rewrite rules?

I have tried things like calling `load_plugin_routes()` or this:
```php
require_once MVC_PLUGIN_PATH.'core/loaders/mvc_public_loader.php';
$public_loader = new MvcPublicLoader();
$public_loader->init();
$public_loader->load_rewrite_rules();
$public_loader->flush_rewrite_rules();
```

But I got this error:
```
Fatal error: Call to a member function add_query_var() on null in /code/wordpress/wp-includes/rewrite.php on line 47
```

Thanks for your help

**Comment by cyberscribe** [comment]
Hi amarcadet,

You should not need to directly access the public_loader, but instead specify all routes using [MVCRouter](http://wpmvc.org/documentation/routing/) static method calls. However, for performance reasons, the rewrite rules specified this way are only applied and flushed at time of plugin activation. 

If you change them subsequent to activating the plugin, however (i.e. during development), you can re-apply them by clicking [save changes](https://codex.wordpress.org/Settings_Permalinks_Screen#Save_Changes) in the Permalinks Settings Screen. This method flushes and re-loads all rewrite rules for Wordpress, including those loaded by wp-mvc.

I hope this helps!

Best,
Robert

**Comment by amarcadet** [comment]
Thanks for the quick reply, I'd hope for a solution that doesn't require to click on something, but that will be enough!
