### ISSUE TITLE
Is it ok to override views_path?

### ISSUE THREAD

**Issue by amarcadet** [tombenner/wp-mvc#68]
By inspecting your code I have found that you automatically look for templates in a folder using a pluralize version of the model name.

In my case, my controller is not bound to a specific model, and the default behavior is to look into a folder named `registers`. In order to fix this, I have override the property `views_path` (see below), but was wondering if it is ok, or if it could lead to unexpected behavior since this property is not declared as such in the `MvcController` class.

```php
class RegisterController extends MvcPublicController
{
    public function __construct()
    {
        parent::__construct();
        $this->views_path = 'register/';
    }
}
```

Thanks for your help!

**Comment by tombenner** [comment]
We really shouldn't use the model to construct the view path; that was a poor (and probably rushed) design decision on my part. I've typically tried to follow Rails' conventions for decisions like this, so I'm thinking that we should use the controller name to construct the view path and possibly also support a [prepend_view_path](http://edgeapi.rubyonrails.org/classes/AbstractController/ViewPaths/ClassMethods.html#method-i-prepend_view_path)-like method, or at least a setter method for `views_path`.

Those are just some quick thoughts. Any thoughts on what the best implementation should be, @cyberscribe or @amarcadet?

**Comment by cyberscribe** [comment]
I agree that in classic MVC, a model has no business even knowing that views exist. I like the idea of the controller name governing this much better. I also like the idea of making views_path itself private and offering a getter/setter. @tombenner is that something you might be interested in working on?

@amarcadet I will also mention that if you are just looking for an autoloader, the app/models directory does not need to be populated only by classes that extend MvcModel. I have often put in API classes that, for example, perform remote REST calls. They are legitimate models, too--even if they don't touch a database on this side of the network. And they get auto-loaded for use throughout the application as a normal class.

You can also always put something into the main plugin file like:

    function my_registers_autoload( $ClassName ) {
        if (!class_exists($ClassName)) {
            $file = plugin_dir_path( __FILE__ ) . 'registers/' . $ClassName . '.php';
            if (file_exists($file)) {
                require_once($file);
            }
        }
    }
    spl_autoload_register('my_registers_autoload');

wp-mvc does not preclude using standard Wordpress or PHP conventions for OOP inside the main plugin area; it just supplements them with MVC pattern best-practices.

I hope this helps, and thanks for pointing this architectural consideration out for us!

**Comment by amarcadet** [comment]
Nevermind I have found the method `render_view` to change the path.
```php
$this->render_view('register/index');
```

**Comment by cyberscribe** [comment]
Yes, this is the preferred method if you just want to specify a view in the
controller logic. Obviously, there are bigger implications if you want to
override the default path completely. ``render_view()`` is what I use most
often in my plugins.

**Comment by cyberscribe** [comment]
Yes, this is the preferred method if you just want to specify a view in the
controller logic. Obviously, there are bigger implications if you want to
override the default path completely. `render_view()` is what I use most
often in my plugins. Rather than inspecting code, be sure to check out the [Documentation](http://wpmvc.org/documentation/) for recommended approaches.
