### ISSUE TITLE
Stand-alone feature?

### ISSUE THREAD

**Issue by damianoporta** [tombenner/wp-mvc#74]
Hello,
what do you think about creating a stand-alone version of this framework ?
At the moment a plugin that uses this framework needs wp-mvc as dependence (a different plugin that must be downloaded and activated) what about if we incorporate it?

**Comment by cyberscribe** [comment]
Hi Damiano,

It is an interesting idea. I'm not sure in practical terms how it would work. If you have ideas, or want to try something on a fork, I'd be interested in knowing more.

Best,
Robert
