### ISSUE TITLE
Support Password Fields in Form Helper

### ISSUE THREAD

**Issue by brandtOSS** [tombenner/wp-mvc#76]
It would be great if there was support in `MvcFormHelper` for HTML password fields.

*Example:*

```php
echo $this->form->input('user_pw', array('type' => 'password', 'label' => 'Your Password', 'required' => true));
```
Or alternatively:
```php
echo $this->form->password('user_pw', array('label' => 'Your Password', 'required' => true));

**Comment by cyberscribe** [comment]
Nice idea! Want to implement and submit a pull request?

**Comment by brandtOSS** [comment]
Sure :-)
Hope the code is up to the standards.
Sory about opening another issue with the pull request https://github.com/tombenner/wp-mvc/pull/77, I am not sure whether I also can attach the pull request to this issue.

**Comment by cyberscribe** [comment]
Thanks for doing this! I'll try to have a look at the code this weekend.
