### ISSUE TITLE
Possible to have an admin controller with no model?

### ISSUE THREAD

**Issue by samwilson** [tombenner/wp-mvc#80]
[Line 95 of `core/loaders/mvc_admin_loader.php`](https://github.com/tombenner/wp-mvc/blob/5247212fbece86146a125dcb1e7d913d734dcae0/core/loaders/mvc_admin_loader.php#L95) says that "not every controller must have a corresponding model", but there are a number of errors that seem to come up when trying to create a simple non-model-associated controller.

Is it possible, or am I chasing the wrong thing?

**Comment by Lamabada** [comment]
I've created a small fix for that fatal error and I've added it to my pull request.

https://github.com/Lamabada/wp-mvc/commit/ecdf157a87e881a865cce4647297a329dedea21c
