### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by ctaylor11** [tombenner/wp-mvc#82]
I have a wordpress website and cant log into my dashboard due to a problem with the WP-MVC plugin stated below.  I was curious if you have ever seen this or could point me in the right direction to resolve this problem.

[MVC] Fatal Error: The file "models/prod_option.php" couldn't be found in any apps.
Thrown on line 18 of /home5/vicmobil/public_html/wp-content/plugins/wp-mvc/core/functions/functions.php

Thanks!

**Comment by cyberscribe** [comment]
Hi Craig,

Looks like maybe you are calling mvc_model('ProdOption') somewhere in your wp-mvc-derived plugin. Is that possible? And if so, is there actually an app/models/prod_option.php file with a "class ProdOption" definition up top?

That seems like the most likely cause here.
