### ISSUE TITLE
Route parameters not parsed into controllers params

### ISSUE THREAD

**Issue by lordthorzonus** [tombenner/wp-mvc#83]
Hi! I tried to update from 1.2 to 1.3.3 but after this update only id parameters are parsed into controllers $this->params array. 

I tried to hardcode new parameters into mvc_loader.php on line 22:
``` $this->query_vars = array('mvc_controller','mvc_action','mvc_id','mvc_extra');```
And this helped. It seems that the additional query_vars aren't just loaded from my routes file. Am I missing some configurations or is this a bug?

**Comment by cyberscribe** [comment]
Have you tried flushing the rewrite rules after adding new routes?

See: (I am getting a 404 when I add a new route)[https://wordpress.org/plugins/wp-mvc/faq/#I+am+getting+a+404+when+I+add+a+new+route]

**Comment by lordthorzonus** [comment]
Updating permalinks or reactivating the plugin didn't help. But after doing ```  flush_rewrite_rules( true ); ```  on start of functions.php did the trick. Thanks a thousand! :)

**Comment by cyberscribe** [comment]
Sure. You take a big performance hit for flushing, so don't keep that line
in there unless you want to really tax your database. :)

**Comment by lordthorzonus** [comment]
Just noticed that removing the <?php flush_rewrite_rules( true ); ?> makes the params break again. So somehow the rewrite rules aren't saved?

**Comment by cyberscribe** [comment]
You'll need to call your own flush each time if you are hard-coding in the
query vars, but that's not how wp-mvc is intended to work.

Here are some sample rewrite rules that are active on my website now, in
case these syntax examples help you to get what you want:

`MvcRouter::public_connect('{:controller}/{:id:[\d]+}{:extra:(.*)}',
array('action' => 'show'));
MvcRouter::public_connect('{:controller}/{:action}/{:id:[\d]+}');`

Best,
Robert

**Comment by lordthorzonus** [comment]
I understand the syntax. ``` MvcRouter::public_connect('events/{:country:[\S]+}/{:slug:[\S]+}/{:id:[\d]+}', array('controller' => 'events', 'action' => 'show')); ``` This is a example from our site. It works on 1.2 but after updating to 1.3.3 the country and slug params aren't passed to the controller. So this is an intended change? Calling the flush on functions file and hard coding these feels kinda hacky. 

Thanks for the support! :)

**Comment by cyberscribe** [comment]
Hi Juuso,

Sorry about that!

In order to stop flushing rewrite rules on every page load (!) we had to
limit the vocabulary to just controller, action, id, and extra. That's why
your country and slug aren't working in 1.3.3.

I think there must be a good way to make any label work again, but I
haven't had time to look at it. If you are interested in having a look,
please do submit a pull request if you find out how to make it accept any
and all words again without having to flush rewrite rules on page loads.

Best,
Robert
