### ISSUE TITLE
Are there any unit tests available?

### ISSUE THREAD

**Issue by davideugenepratt** [tombenner/wp-mvc#87]
I've seen somewhere in the comments in the code a mention about tests and I see that there are "tested up to x.x" commit messages so I was wondering if there are any unit tests available. If so can they be added to the repo?

**Comment by cyberscribe** [comment]
Hi David,

It would be great to have a full batery of PHPUnit tests to run on wp-mvc. Current, we don't. The "tested up to" is from acceptance testing after major changes, and the x.x is the version of WordPress we used.

I'd welcome anyone wanting to contribute unit tests for wp-mvc using the WordPress unit testing framework and/or Travis CI.
