### ISSUE TITLE
Error running ./wpmvc generate plugin mypluginname

### ISSUE THREAD

**Issue by otherjohn** [tombenner/wp-mvc#92]
I am getting the following error and it doesn't create the plugin when I run ./wpmvc generate plugin mypluginname

 Warning: mysqli_real_connect(): (HY000/2002): No such file or directory in /Repository/Personal/this_project/CODE/plugins/BMS/wordpress/wp-includes/wp-db.php on line 1452

Error establishing a database connection

The odd thing is that wordpress is running just fine. I am running locally too. No reason to get this error.

**Comment by otherjohn** [comment]
Actually, I just exported the correct MAMP php path and now I get another error:
otice: Undefined index: HTTP_HOST in /Repository/Personal/this_project/CODE/plugins/BMS/wordpress/wp-includes/ms-settings.php on line 30

Warning: Cannot modify header information - headers already sent by (output started at /Repository/Personal/this_project/CODE/plugins/BMS/wordpress/wp-includes/ms-settings.php:30) in /Repository/Personal/this_project/CODE/plugins/BMS/wordpress/wp-includes/ms-settings.php on line 162

**Comment by cyberscribe** [comment]
Please try with all other plugins disabled, using TwentyTwelve theme. It sounds like something else is referencing HTTP_HOST in a way that triggers an error when attempting command-line WP.

**Comment by curtisolson** [comment]
I had the same DB connection error and this resolved it for me. Running MAMP Pro on OSX. 

On Map dashboard click Webstart in upper right. That opens this page. http://localhost/MAMP/?language=English

Look for socket value. Mine was this
`Socket	/Applications/MAMP/tmp/mysql/mysql.sock`

In wp_config, change localhost to localhost:/Applications/MAMP/tmp/mysql/mysql.sock 
Or whatever is the value or your Socket. Plugin created properly after that.
