### ISSUE TITLE
Feature: Baking Functionality

### ISSUE THREAD

**Issue by pascalknecht** [tombenner/wp-mvc#98]
A baking Functionality like in CakePHP would be awesome. Define hasmany, belongsto, and other relationships in terminal while baking the code

http://book.cakephp.org/3.0/en/bake/usage.html

**Comment by cyberscribe** [comment]
It's a fun idea. Could be an extension of the existing shell script. Also interested in closer (optional) integration with wp-cli. If you're interested in doing any of this, I'd be happy to code review a pull request.
